# -*- coding: utf-8 -*-
"""
/***************************************************************************
 HereGeocoder
                                 A QGIS plugin
 With this plugin you can geocode multiple adresses from JSON file, using HERE services with your API key
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-01-12
        copyright            : (C) 2020 by Aldres
        email                : aldres98@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load HereGeocoder class from file HereGeocoder.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .here_geocoder import HereGeocoder
    return HereGeocoder(iface)
